<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Starx\Zf2FancyMenuBuilder\Block'     => __DIR__ . '//src/FancyMenu/Block.php',
  'Starx\Zf2FancyMenuBuilder\Column'    => __DIR__ . '//src/FancyMenu/Column.php',
  'Starx\Zf2FancyMenuBuilder\Common'    => __DIR__ . '//src/FancyMenu/Common.php',
  'Starx\Zf2FancyMenuBuilder\FancyMenu' => __DIR__ . '//src/FancyMenu/FancyMenu.php',
  'Starx\Zf2FancyMenuBuilder\Module'    => __DIR__ . '//Module.php',
);
